# Generated by Django 5.0.2 on 2024-02-19 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.therapist')),
                ('participants', models.ManyToManyField(to='backend.user')),
            ],
        ),
    ]
