# Generated by Django 5.0.2 on 2024-02-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='participants',
            field=models.ManyToManyField(default=None, to='backend.user'),
        ),
    ]
