# Generated by Django 5.0.2 on 2024-02-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmodel_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='token',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
