# Generated by Django 5.0.2 on 2024-02-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chatmodel_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='roomID',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
